---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - import_tasks: "tasks/gitconfig.yml"
      tags: ['gitconfig']

    - import_tasks: tasks/inconsolata.yml
      when: install_inconsolata
      tags: ['inconsolata']

    - import_tasks: tasks/rvm.yml
      when: install_rvm
      tags: ['rvm']

    - import_tasks: tasks/oh-my-zsh.yml
      when: install_oh_my_zsh
      tags: ['oh-my-zsh']

    - import_tasks: tasks/osx.yml
      when: configure_osx
