- name: Detect oh-my-zsh binary
  stat:
    path: '~/.oh-my-zsh/oh-my-zsh.sh'
  register: oh_my_zsh_install

- name: Install oh-my-zsh
  shell: "sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc\""
  when: not oh_my_zsh_install.stat.exists

